### ISSUE TITLE
Extend myactuator_library to work with X6 motors

### ISSUE THREAD

**Issue by rj-mac** [wvu-urc/myactuator_lib#2]
This library currently lets us control the MyAcuator RMD-X10 motors, which will be used on the 2024 rover's drivetrain. We also want to use this library for controlling Wanderer 2's RMD-X6 drive motors. This will be a big step in converting Wanderer 2 to a testing platform for this year's code. Reach out to @nate-adkins for help with this.

**Comment by nate-adkins** [comment]
Moving to done. Control board on both models are same
